Update VPCv1.yml

diff --git a/VPCv1.yml b/VPCv1.yml
--- a/VPCv1.yml
+++ b/VPCv1.yml
@@ -32,7 +32,7 @@ Resources:
       Tags:
         - Key: Name
           Value: GovClientVPC
-    
+ #-----------------------Subnet Block-----------------------------   
   PublicSubnet1:
     Type: AWS::EC2::Subnet
     Properties:
@@ -86,7 +86,14 @@ Resources:
         Value: "Web Subnet 2"
       - Key: subnet-type
         Value: Private
-  #RouteTable and associate
+  
+  #----------------------------RouteTable and associate------------------------------------------
+  #publicEIP
+  WebServerEIP:
+    Type: AWS::EC2::EIP
+    Properties:
+      Domain: vpc
+      InstanceId: !Ref WebServerInstance
   #Public
   PublicSubnetRouteTable:
     Type: AWS::EC2::RouteTable
@@ -119,23 +126,7 @@ Resources:
     DependsOn:
       - VPCGW
   
-  #InternetGateway IgW defined
-  VPCIGW:
-    Type: AWS::EC2::InternetGateway
-    Properties:
-      Tags:
-        - Key: Name
-          Value: VPCIGW
-
-  #VPCGatewayAttachment binds VPC and IgW
-  VPCGW:
-    Type: AWS::EC2::VPCGatewayAttachment
-    Properties:
-      VpcId:
-        Ref: MyVPC
-      InternetGatewayId:        #The ID of the internet gateway.
-        Ref: VPCIGW
-      #VpnGatewayId: String     You must specify either InternetGatewayId or VpnGatewayId, but not both.
+  
   #PrivateRT
   NatEIP1:
     Type: AWS::EC2::EIP
@@ -213,7 +204,25 @@ Resources:
         - Key: Network
           Value: Public
       VpcId: !Ref MyVPC
+###-------------IgW and binding-------------------------------------------------------------###
+  #InternetGateway IgW defined
+  VPCIGW:
+    Type: AWS::EC2::InternetGateway
+    Properties:
+      Tags:
+        - Key: Name
+          Value: VPCIGW
 
+  #VPCGatewayAttachment binds VPC and IgW
+  VPCGW:
+    Type: AWS::EC2::VPCGatewayAttachment
+    Properties:
+      VpcId:
+        Ref: MyVPC
+      InternetGatewayId:        #The ID of the internet gateway.
+        Ref: VPCIGW
+      #VpnGatewayId: String     You must specify either InternetGatewayId or VpnGatewayId, but not both.
+  
   #-------------SecurityGroups Block-------------------------------------
   BastionSecurityGroup:
       Type: AWS::EC2::SecurityGroup
@@ -302,75 +311,75 @@ Resources:
   
   WebServerInstance:
     Type: AWS::EC2::Instance
-    Metadata:
-      AWS::CloudFormation::Init:
-        config:
-          packages:
-            yum:
-              httpd: []
-              php: []
+    # Metadata:
+    #   AWS::CloudFormation::Init:
+    #     config:
+    #       packages:
+    #         yum:
+    #           httpd: []
+    #           php: []
 
-          files:
-            /var/www/html/index.php:
-              content: |
-                <!DOCTYPE html>
-                <html>
-                <body>
-                  <center>
+    #       files:
+    #         /var/www/html/index.php:
+    #           content: |
+    #             <!DOCTYPE html>
+    #             <html>
+    #             <body>
+    #               <center>
 
-                    <?php
-                    # Get the instance ID from meta-data and store it in the $instance_id variable
-                    $url = "http://169.254.169.254/latest/meta-data/instance-id";
-                    $instance_id = file_get_contents($url);
-                    # Get the instance's availability zone from metadata and store it in the $zone variable
-                    $url = "http://169.254.169.254/latest/meta-data/placement/availability-zone";
-                    $zone = file_get_contents($url);
-                    # Get the instance AMI ID and store it in the $ami_id variable
-                    $url = "http://169.254.169.254/latest/meta-data/ami-id";
-                    $ami_id = file_get_contents($url);
-                    ?>
+    #                 <?php
+    #                 # Get the instance ID from meta-data and store it in the $instance_id variable
+    #                 $url = "http://169.254.169.254/latest/meta-data/instance-id";
+    #                 $instance_id = file_get_contents($url);
+    #                 # Get the instance's availability zone from metadata and store it in the $zone variable
+    #                 $url = "http://169.254.169.254/latest/meta-data/placement/availability-zone";
+    #                 $zone = file_get_contents($url);
+    #                 # Get the instance AMI ID and store it in the $ami_id variable
+    #                 $url = "http://169.254.169.254/latest/meta-data/ami-id";
+    #                 $ami_id = file_get_contents($url);
+    #                 ?>
 
-                    <h2>EC2 Instance ID: <?php echo $instance_id ?></h2>
-                    <h2>Availability Zone: <?php echo $zone ?></h2>
-                    <h2>AMI ID: <?php echo $ami_id ?></h2>
+    #                 <h2>EC2 Instance ID: <?php echo $instance_id ?></h2>
+    #                 <h2>Availability Zone: <?php echo $zone ?></h2>
+    #                 <h2>AMI ID: <?php echo $ami_id ?></h2>
 
-                  </center>
-                </body>
-                </html>
-              mode: 000644
-              owner: apache
-              group: apache
+    #               </center>
+    #             </body>
+    #             </html>
+    #           mode: 000644
+    #           owner: apache
+    #           group: apache
 
-            /etc/cfn/cfn-hup.conf:
-              content: !Sub |
-                [main]
-                stack=${AWS::StackId}
-                region=${AWS::Region}
-                interval=1
-              mode: 000400
-              owner: root
-              group: root
+    #         /etc/cfn/cfn-hup.conf:
+    #           content: !Sub |
+    #             [main]
+    #             stack=${AWS::StackId}
+    #             region=${AWS::Region}
+    #             interval=1
+    #           mode: 000400
+    #           owner: root
+    #           group: root
 
-            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
-              content: !Sub |
-                [cfn-auto-reloader-hook]
-                triggers=post.update
-                path=Resources.WebServerInstance.Metadata.AWS::CloudFormation::Init
-                action=/opt/aws/bin/cfn-init --stack ${AWS::StackName} --resource WebServerInstance --region ${AWS::Region}
-                runas=root
+    #         /etc/cfn/hooks.d/cfn-auto-reloader.conf:
+    #           content: !Sub |
+    #             [cfn-auto-reloader-hook]
+    #             triggers=post.update
+    #             path=Resources.WebServerInstance.Metadata.AWS::CloudFormation::Init
+    #             action=/opt/aws/bin/cfn-init --stack ${AWS::StackName} --resource WebServerInstance --region ${AWS::Region}
+    #             runas=root
 
-          services:
-            sysvinit:
-              httpd:
-                enabled: true
-                ensureRunning: true
+    #       services:
+    #         sysvinit:
+    #           httpd:
+    #             enabled: true
+    #             ensureRunning: true
 
-              cfn-hup:
-                enabled: true
-                ensureRunning: true
-                files:
-                  - /etc/cfn/cfn-hup.conf
-                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
+    #           cfn-hup:
+    #             enabled: true
+    #             ensureRunning: true
+    #             files:
+    #               - /etc/cfn/cfn-hup.conf
+    #               - /etc/cfn/hooks.d/cfn-auto-reloader.conf
     Properties:
       SubnetId: !Ref PublicSubnet1
       #IamInstanceProfile: !Ref WebServerInstanceProfile
@@ -383,16 +392,16 @@ Resources:
       Tags:
         - Key: Name
           Value:  webserverInstancePhp
-      UserData:
-        Fn::Base64:
-          !Sub |
-          #!/bin/bash -xe
-          # Update aws-cfn-bootstrap to the latest
-          yum install -y aws-cfn-bootstrap
-          # Call cfn-init script to install files and packages
-          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServerInstance --region ${AWS::Region}
-          # Call cfn-signal script to send a signal with exit code
-          /opt/aws/bin/cfn-signal --exit-code $? --stack ${AWS::StackName} --resource WebServerInstance --region ${AWS::Region}
+      # UserData:
+      #   Fn::Base64:
+      #     !Sub |
+      #     #!/bin/bash -xe
+      #     # Update aws-cfn-bootstrap to the latest
+      #     yum install -y aws-cfn-bootstrap
+      #     # Call cfn-init script to install files and packages
+      #     /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServerInstance --region ${AWS::Region}
+      #     # Call cfn-signal script to send a signal with exit code
+      #     /opt/aws/bin/cfn-signal --exit-code $? --stack ${AWS::StackName} --resource WebServerInstance --region ${AWS::Region}
           
           # yum install httpd php php-mysql -y
           # amazon-linux-extras install -y php7.2
@@ -406,9 +415,21 @@ Resources:
           # chown -R apache:apache wp-content
           # service httpd start
           # chkconfig httpd on
-      # UserData:
-      #   Fn::Base64: |
-      #     #!/bin/bash
+      UserData:
+        Fn::Base64: |
+          #!/bin/bash
+          yum install httpd php php-mysql -y
+          amazon-linux-extras install -y php7.2
+          cd /var/www/html
+          wget https://wordpress.org/wordpress-5.4.1.tar.gz
+          tar -xzf wordpress-5.4.1.tar.gz
+          cp -r wordpress/* /var/www/html/
+          rm -rf wordpress
+          rm -rf wordpress-5.4.1.tar.gz
+          chmod -R 755 wp-content
+          chown -R apache:apache wp-content
+          service httpd start
+          chkconfig httpd on
       #     yum update -y
       #     yum install -y httpd php
       #     systemctl start httpd
@@ -433,21 +454,21 @@ Resources:
       #           # Get the instance's availability zone from metadata and store it in the $zone variable
       #           $url = "http://169.254.169.254/latest/meta-data/placement/availability-zone";
       #           $zone = file_get_contents($url);
+      #           # Get the instance AMI ID and store it in the $ami_id variable
+      #           $url = "http://169.254.169.254/latest/meta-data/ami-id";
+      #           $ami_id = file_get_contents($url);
       #           ?>
 
       #           <h2>EC2 Instance ID: <?php echo $instance_id ?></h2>
       #           <h2>Availability Zone: <?php echo $zone ?></h2>
+      #           <h2>AMI ID: <?php echo $ami_id ?></h2>
 
       #         </center>
       #       </body>
       #       </html>
       #     EOF
 
-  WebServerEIP:
-    Type: AWS::EC2::EIP
-    Properties:
-      Domain: vpc
-      InstanceId: !Ref WebServerInstance
+  
   
   
   #-------------------IAM---------------------------------------
